/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PART_B_H_RPCGEN
#define _PART_B_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct input {
	int a;
	int b;
	char *exec;
};
typedef struct input input;

#define PART_B_PROG 0x12345678
#define PART_B_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define blackbox 1
extern  char ** blackbox_1(input *, CLIENT *);
extern  char ** blackbox_1_svc(input *, struct svc_req *);
extern int part_b_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define blackbox 1
extern  char ** blackbox_1();
extern  char ** blackbox_1_svc();
extern int part_b_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_input (XDR *, input*);

#else /* K&R C */
extern bool_t xdr_input ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PART_B_H_RPCGEN */
